name: Bug report
description: Create a bug report to help us improve
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing to make Data Monitor better by reporting a bug.

        Please fill in as much information as possible about your bug.
  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      options:
        - label: "I am able to reproduce the bug with the [latest version](https://github.com/itsdrnoob/DataMonitor/releases/latest)."
          required: true
        - label: "I made sure that there are no existing issues - [open](https://github.com/itsdrnoob/DataMonitor/issues) or [closed](https://github.com/itsdrnoob/DataMonitor/issues?q=is%3Aissue+is%3Aclosed)."
          required: true
        - label: "I have taken the time to fill in all the required details in an appropriate descriptive way. I understand that the bug report will be dismissed otherwise."
          required: true
        - label: "This issue contains only one bug."
          required: true
  - type: input
    id: app-version
    attributes:
     label: Affected app version
     description: "In which version of Data Monitor did you encounter the bug?"
     placeholder: "vX.X.X - Can be seen in the app from the 'About' section in settings"
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce the bug
      description: |
        What did you do for the bug to show up?

        If you can't cause the bug to show up again reliably (and hence don't have a proper set of steps to give us), please still try to give as many details as possible on how you think you encountered the bug.
      placeholder: |
        1. Go to '...'
        2. Press on '....'
        3. Swipe down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: |
        A clear and concise description of what you expected to happen.
  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual behavior
      description: |
        A clear and concise description of what happens with the steps given above.
  - type: textarea
    id: screen-media
    attributes:
      label: Screenshots/Screen recordings
      description: |
        If applicable, add screenshots or a screen recording to help explain your problem.
        GitHub supports uploading them directly in the text box.
        If your file is too big for Github to accept, try to compress it (ZIP-file) or feel free to paste a link to an image/video hoster here instead.
  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: |
        If your bug includes a crash, paste the logs copied from crash reporter here.
  - type: input
    id: device-os-info
    attributes:
     label: Affected Android/Custom ROM version
     description: |
      With what operating system (+ version) did you encounter the bug?
     placeholder: "Example: Android 12 / LineageOS 18.1"
  - type: input
    id: device-model-info
    attributes:
     label: Affected device model
     description: |
      On what device did you encounter the bug?
     placeholder: "Example: Pixel 6 Pro / Samsung Galaxy S20"
  - type: textarea
    id: additional-information
    attributes:
      label: Additional context
      description: |
        Any other information you'd like to include regarding the bug.