name: Feature request
description: Suggest an idea for this project
body:
  - type: markdown
    attributes:
      value: |
        Thank you for contributing to make Data Monitor better by suggesting a feature.

        Your ideas are highly welcome!
  - type: checkboxes
    id: checklist
    attributes:
      label: "Checklist"
      options:
        - label: "I made sure that there are no similar feature requests - [open](https://github.com/itsdrnoob/DataMonitor/issues) or [closed](https://github.com/itsdrnoob/DataMonitor/issues?q=is%3Aissue+is%3Aclosed)."
          required: true
        - label: "I have taken the time to fill in all the required details in an appropriate descriptive way. I understand that the feature request will be dismissed otherwise."
          required: true
        - label: "This issue contains only one feature request."
          required: true
  - type: textarea
    id: feature-description
    attributes:
      label: Describe the Feature you'd like
      description: |
        A clear and concise description of the feature.
    validations:
      required: true
  - type: textarea
    id: feature-reason
    attributes:
      label: Why do you want this feature?
      description: |
        A clear and concise description of why you want this feature.
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.